### PR TITLE
[minix] Fix Minix umount super block unchecked flag, add new debug mechanism

### LINKED ISSUE #437: 'shutdown' and 'reboot' should un-mount rootfs upon termination
As in the subject. The `shutdown` command does not seem to do anything (the system is still alive after `System halted` message) while rebooting the system with the `reboot` command results in un-checked rootfs filesystem warning message upon the subsequent system boot.

### PR DESCRIPTION
**Pull request by ghaerr**
This fixes #437. The Minix superblock is now force written on remounts, rather than previously trying to keep track of its status (which didn't work after `sync`). The `reboot` command does a sync, then mounts the root filesystem read-only, then sleeps for three seconds and reboots.

The `sleep` system call is not implemented (I recommend removing it entirely), and libc `sleep` is broken, so `sleep` is now (properly) written in reboot.c, for the time being. I will have a PR for libc `sleep`, although making any changes in `libc/system/sleep.c` are ignored (a problem in libc make?).

It took quite a bit to trace this down, and I've added an improved debug mechanism.
This mechanism allows for very interesting tracing, I will comment more on it after the next commit, which expands on it for the broken `signal` processing in ELKS.

@jbruchon, please commit this PR before my next PR (signal fix), as that may help with merge issues on my second PR.

### CODE REVIEW

File: libc/include/unistd.h [hunk 1]
```diff
@@ -52,9 +52,9 @@ int isatty (int fd);
 off_t lseek (int fildes, off_t offset, int whence);
 int unlink(const char *fname);
 
-pid_t fork ();
-pid_t getpid ();
-pid_t setsid ();
+pid_t fork(void);
+pid_t getpid(void);
+pid_t setsidvoid();
```
Comment (mfld-fr) [inline libc/include/unistd.h]: Not a typo here ?

**Review by mfld-fr — CHANGES_REQUESTED** [review]

File: libc/include/unistd.h (hunk 1 above)
Comment (ghaerr) [reply libc/include/unistd.h]: Sure is, thanks for finding this. Because of the combined branchs (I created sup first, then sig as a sub-branch, but GitHub is combing the second one), I'd like to fix this in another commit, if that's  ok.
